CREATE TABLE loan_application (
    loan_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    loan_type_id BIGINT NOT NULL,
    application_number VARCHAR(50) NOT NULL,
    loan_status VARCHAR(30) NOT NULL,
    loan_amount DECIMAL(15, 2) NOT NULL,
    approved_amount DECIMAL(15, 2) NULL,
    loan_tenure_months INT NOT NULL,
    interest_rate DECIMAL(5, 2) NOT NULL,
    purpose VARCHAR(500) NOT NULL,
    monthly_income DECIMAL(15, 2) NOT NULL,
    existing_emis DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    emi DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    CONSTRAINT uk_loan_application_number UNIQUE (application_number),
    CONSTRAINT fk_loan_application_customer_profile FOREIGN KEY (customer_id) REFERENCES customer_profile(customer_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_loan_application_loan_type FOREIGN KEY (loan_type_id) REFERENCES loan_type(loan_type_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    INDEX idx_loan_application_status (loan_status),
    INDEX idx_loan_application_number (application_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
